import {useEffect,useState,type ReactNode} from 'react';
import {ApiClient,CapabilityNotice,DashboardShell,DataTable,Field,JsonDisclosure,LocaleProvider,MetricCard,PageHeader,Panel,RemoteState,SubmitButton,formatXaf,loadRuntimeConfig,useHashRoute,useMutation,useRemote} from '@kombe/dashboard-core';
import {DirectionApi,type Economics} from './api';
const messages={app:{fr:'Direction & Analytics',en:'Direction & Analytics'}} as const;
const NAV=[{path:'/',label:'Vue d’ensemble',icon:'◫'},{path:'/funnel',label:'Funnel',icon:'↘'},{path:'/cohorts',label:'Cohortes',icon:'◎'},{path:'/economics',label:'Économie unitaire',icon:'¤'},{path:'/risks',label:'Risques',icon:'!'},{path:'/gates',label:'Gates d’extension',icon:'◆'}] as const;
function Overview({api}:{api:DirectionApi}){const r=useRemote(s=>api.risks(s),[api],{isEmpty:d=>d.length===0});const g=useRemote(s=>api.extensionCheck(s),[api]);return <><PageHeader title="Pilotage KÓMBE" description="Mesures agrégées/pseudonymisées C18 uniquement. Aucun champ financier individuel."/><div className="k-grid"><div className="k-span-6"><Panel title="Gate d’extension"><RemoteState state={g.state} onRetry={g.reload}>{d=><JsonDisclosure value={d}/>}</RemoteState></Panel></div><div className="k-span-6"><Panel title="Risques"><RemoteState state={r.state} onRetry={r.reload} emptyTitle="Aucun risque retourné">{d=><MetricCard label="Risques enregistrés" value={String(d.length)}/>}</RemoteState></Panel></div></div></>}
function FunnelPage({api}:{api:DirectionApi}){const[id,setId]=useState('');const[gid,setGid]=useState('');const[selected,setSelected]=useState('');const[selGroup,setSelGroup]=useState('');const q=useRemote(s=>api.funnel(selected,selGroup,s),[api,selected,selGroup],{enabled:!!selected&&!!selGroup});return <><PageHeader title="Funnel d’adoption" description="Comptes agrégés ; individualFinancialFields doit rester 0. En mode réel, le groupe porteur scope la lecture (RLS)."/><Panel><form onSubmit={e=>{e.preventDefault();setSelected(id.trim());setSelGroup(gid.trim())}}><Field label="Cohort ID" inputProps={{value:id,onChange:e=>setId(e.target.value),required:true}}/><Field label="Group ID" inputProps={{value:gid,onChange:e=>setGid(e.target.value),required:true}}/><button className="k-button k-button-primary">Charger</button></form></Panel><div style={{height:16}}/><Panel><RemoteState state={q.state} onRetry={q.reload}>{d=><><div className="k-metrics"><MetricCard label="Champs financiers individuels" value={String(d.individualFinancialFields)} hint="Garde structurelle : 0"/></div><DataTable rows={d.steps} rowKey={r=>r.step} columns={[{header:'Étape',render:r=>r.step},{header:'Compte',render:r=>String(r.count)}]}/></>}</RemoteState></Panel></>}
function Cohorts({api}:{api:DirectionApi}){const[id,setId]=useState('');const[selected,setSelected]=useState('');const q=useRemote(s=>api.cohort(selected,s),[api,selected],{enabled:!!selected});return <><PageHeader title="Cohortes" description="Un cycle correspond à une rotation complète."/><Panel><form onSubmit={e=>{e.preventDefault();setSelected(id.trim())}}><Field label="Group ID" inputProps={{value:id,onChange:e=>setId(e.target.value),required:true}}/><button className="k-button k-button-primary">Consulter</button></form></Panel><div style={{height:16}}/><Panel><RemoteState state={q.state} onRetry={q.reload}>{d=><div className="k-metrics"><MetricCard label="Membres" value={String(d.memberCount)}/><MetricCard label="Tours terminés" value={String(d.roundsCompleted)}/><MetricCard label="Cycles complets" value={String(d.completedCycles)}/><MetricCard label="Rétention 3 cycles" value={d.eligibleThreeCycleRetention?'Éligible':'Non éligible'}/></div>}</RemoteState></Panel></>}
function EconomicsResult({data}:{data:Economics}){return <><div className="k-metrics" style={{marginTop:20}}><MetricCard label="Payeurs réels" value={String(data.realPayers)}/><MetricCard label="Taux réel" value={`${data.paymentRealPercent}%`}/><MetricCard label="Coût total" value={formatXaf(data.totalCostMinor)}/><MetricCard label="Gate G2" value={data.gateG2Met?'Atteinte':'Non atteinte'}/></div><JsonDisclosure value={data}/></>}
function EconomicsPage({api}:{api:DirectionApi}){const[form,setForm]=useState({exposedMembers:'',paidCount:'',promisedCount:'',supportMinutes:'',supportCostPerMinuteMinor:'',infrastructureCostMinor:'',cancellations:'',taxesMinor:''});const update=(k:keyof typeof form,v:string)=>setForm(f=>({...f,[k]:v}));const m=useMutation(()=>api.createEconomics(Object.fromEntries(Object.entries(form).map(([k,v])=>[k,k.endsWith('Minor')?v:Number(v)]))));return <><PageHeader title="Économie unitaire" description="Les coûts XAF restent des entiers ; le serveur calcule le snapshot."/><Panel><form onSubmit={e=>{e.preventDefault();m.run(undefined)}} className="k-grid">{Object.entries(form).map(([k,v])=><div className="k-span-4" key={k}><Field label={k} inputProps={{value:v,onChange:e=>update(k as keyof typeof form,e.target.value),required:true,inputMode:'numeric'}}/></div>)}<div className="k-span-12"><SubmitButton busy={m.state.kind==='submitting'}>Calculer et enregistrer côté serveur</SubmitButton></div></form>{m.state.kind==='success'&&<EconomicsResult data={m.state.data}/>}</Panel></>}
function Risks({api}:{api:DirectionApi}){const q=useRemote(s=>api.risks(s),[api],{isEmpty:d=>d.length===0});return <><PageHeader title="Registre des risques" description="Les risques critiques sans contrôle effectif bloquent l’extension."/><Panel><RemoteState state={q.state} onRetry={q.reload} emptyTitle="Aucun risque retourné">{rows=><DataTable rows={rows} rowKey={(_,i)=>String(i)} columns={[{header:'Risque',render:r=><JsonDisclosure value={r}/>} ]}/>}</RemoteState></Panel></>}
function Gates({api}:{api:DirectionApi}){const q=useRemote(s=>api.extensionCheck(s),[api]);return <><PageHeader title="Gates d’extension" description="Décision serveur uniquement ; aucun verdict local n’est fabriqué."/><Panel><RemoteState state={q.state} onRetry={q.reload}>{d=><JsonDisclosure value={d}/>}</RemoteState></Panel></>}
function Dashboard({api,environment}:{api:DirectionApi;environment?:string}){const{path,navigate}=useHashRoute();let page:ReactNode;switch(path){case'/funnel':page=<FunnelPage api={api}/>;break;case'/cohorts':page=<Cohorts api={api}/>;break;case'/economics':page=<EconomicsPage api={api}/>;break;case'/risks':page=<Risks api={api}/>;break;case'/gates':page=<Gates api={api}/>;break;default:page=<Overview api={api}/>;}return <DashboardShell product="Direction & Analytics" nav={NAV} activePath={path} onNavigate={navigate} {...(environment!==undefined?{environment}:{})}>{page}</DashboardShell>}
export function App(){const[ready,setReady]=useState<{api:DirectionApi;environment?:string}|null>(null);const[error,setError]=useState<unknown>(null);useEffect(()=>{loadRuntimeConfig().then(c=>setReady({api:new DirectionApi(new ApiClient({baseUrl:c.apiBaseUrl})),...(c.environment!==undefined?{environment:c.environment}:{})})).catch(setError)},[]);if(error)return <main><CapabilityNotice title="Configuration API absente">{error instanceof Error?error.message:String(error)}</CapabilityNotice></main>;if(!ready)return <main><div className="k-skeleton-stack"><span className="k-skeleton"/></div></main>;return <LocaleProvider messages={messages}><Dashboard {...ready}/></LocaleProvider>}
