/**
 * Erreurs stables du domaine KÓMBE.
 *
 * Chaque violation d'invariant porte un code stable et non divulguant :
 * le code identifie la règle, le message reste générique. Aucune donnée
 * réelle (nom, téléphone, montant d'autrui) ne transite par ces messages.
 * Cf. 01_Audit/ARCHITECTURE_CIBLE.md §Commande, contrat « erreurs stables ».
 */

export type DomainErrorCode =
  | "MONEY_NOT_INTEGER"
  | "MONEY_NEGATIVE"
  | "MONEY_OVER_PER_AMOUNT_CEILING"
  | "MONEY_OVER_SAFE_CEILING"
  | "ROTATION_MEMBERS_MIN"
  | "ROTATION_CONTRIBUTION_POSITIVE"
  | "RESERVATION_INCOHERENTE"
  | "RECONCILIATION_INCOHERENTE"
  | "ELECTORATE_INVALIDE"
  | "VOTE_HORS_LIMITES"
  | "JOUR_INVALIDE"
  | "CSV_TEXTE_REQUIS"
  | "CANONICAL_HORS_ENTIER_SUR"
  | "EVENT_HASH_MISMATCH"
  | "EVENT_CHAIN_BREAK"
  | "MEMBERSHIP_STATE_INVALID"
  | "MEMBERSHIP_ALREADY_ACTIVE"
  | "IDENTITY_NOT_ACTIVE"
  | "ROLE_ACCEPTANCE_REQUIRED"
  | "APPROVER_NOT_DISTINCT"
  | "TOKEN_INVALID"
  | "TOKEN_EXPIRED"
  | "TOKEN_ALREADY_USED"
  | "PASSWORD_TOO_WEAK"
  | "PASSWORD_COMPROMISED"
  | "SESSION_INVALID"
  | "CHANNEL_NOT_VERIFIED"
  | "PRIVILEGE_NOT_GRANTED"
  | "GROUP_STATE_INVALID"
  | "GROUP_READ_ONLY"
  | "CYCLE_START_NOT_READY"
  | "INVITATION_INVALID"
  | "RULES_NOT_ACCEPTED"
  | "RULE_INVALID"
  | "RULE_VERSION_IMMUTABLE"
  | "RULE_ACCEPT_HASH_MISMATCH"
  | "RULE_RETROACTIVE"
  | "SCHEDULE_ROUNDS_MISMATCH"
  | "SCHEDULE_BENEFICIARY_DUPLICATE"
  | "SCHEDULE_MEMBER_UNKNOWN"
  | "SCHEDULE_OBLIGATION_DUPLICATE"
  | "SCHEDULE_FROZEN"
  | "REPLAY_VERSION_UNKNOWN"
  | "CHECKPOINT_MISMATCH"
  | "IDEMPOTENCY_BODY_CONFLICT"
  | "CONTRIBUTION_EXCEEDS_REMAINING"
  | "REFERENCE_JUSTIFICATION_REQUIRED"
  | "CONTRIBUTION_STATE_INVALID"
  | "CONTRIBUTION_ALREADY_COMPENSATED"
  | "VALIDATION_BLOCKED_BY_DISPUTE"
  | "ROUND_CLOSE_BLOCKED_BY_DISPUTE"
  | "DISPUTE_WINDOW_CLOSED"
  | "DISPUTE_REASON_REQUIRED"
  | "DISPUTE_NOT_RESOLVABLE"
  | "DISPUTE_ALREADY_RESOLVED"
  | "DISPUTE_RESOLVER_NOT_DESIGNATED"
  | "DISPUTE_RESOLVER_NOT_INDEPENDENT"
  | "DISPUTE_RESOLUTION_REQUIRED"
  | "FEATURE_PILOT_FORBIDDEN";

export class DomainError extends Error {
  readonly code: DomainErrorCode;
  constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = "DomainError";
    this.code = code;
  }
}
