import type {PropsWithChildren,ReactNode} from 'react';import {useLocale} from '../i18n/locale';import {KombeMark} from './Orbit';
export interface NavItem{readonly path:string;readonly label:string;readonly icon?:string}
export function BrandMark(){return <div className="k-brand" aria-label="KÓMBE — Votre tontine, plus claire."><KombeMark size={36}/><span><strong>KÓMBE</strong><small>Votre tontine, plus claire.</small></span></div>}
export function Panel(p:PropsWithChildren<{title?:string;action?:ReactNode;className?:string}>){return <section className={`k-panel ${p.className??''}`.trim()}>{(p.title||p.action)&&<header className="k-panel-head">{p.title?<h2>{p.title}</h2>:<span/>}{p.action}</header>}{p.children}</section>}
export function PageHeader(p:{title:string;description?:string;actions?:ReactNode}){return <header className="k-page-head"><div><h1>{p.title}</h1>{p.description&&<p>{p.description}</p>}</div>{p.actions&&<div className="k-page-actions">{p.actions}</div>}</header>}
export function MetricCard(p:{label:string;value:string;hint?:string}){return <article className="k-metric"><span>{p.label}</span><strong>{p.value}</strong>{p.hint&&<small>{p.hint}</small>}</article>}
export function StatusChip(p:{status:string;tone?:'ok'|'warn'|'danger'|'neutral'}){return <span className={`k-chip k-chip-${p.tone??'neutral'}`}>{p.status}</span>}
export function KeyValue(p:{label:string;value:ReactNode}){return <div className="k-kv"><span>{p.label}</span><strong>{p.value}</strong></div>}
export function DataTable<T>(p:{rows:readonly T[];rowKey:(r:T,i:number)=>string;columns:readonly {header:string;render:(r:T)=>ReactNode;width?:string}[];caption?:string}){return <div className="k-table-wrap"><table className="k-table">{p.caption&&<caption className="sr-only">{p.caption}</caption>}<thead><tr>{p.columns.map(c=><th key={c.header} style={c.width?{width:c.width}:undefined}>{c.header}</th>)}</tr></thead><tbody>{p.rows.map((r,i)=><tr key={p.rowKey(r,i)}>{p.columns.map(c=><td key={c.header}>{c.render(r)}</td>)}</tr>)}</tbody></table></div>}
export function CapabilityNotice(p:{title:string;contract?:string;children?:ReactNode}){return <section className="k-state k-state-warn" role="status"><strong>{p.title}</strong>{p.contract&&<p>Contrat attendu : <code>{p.contract}</code></p>}{p.children}</section>}
export function JsonDisclosure(p:{value:unknown;label?:string}){return <details className="k-json"><summary>{p.label??'Détails serveur'}</summary><pre>{JSON.stringify(p.value,null,2)}</pre></details>}
export function LocaleToggle(){const{locale,setLocale}=useLocale();return <div className="k-locale" aria-label="Langue"><button type="button" aria-pressed={locale==='fr'} onClick={()=>setLocale('fr')}>FR</button><button type="button" aria-pressed={locale==='en'} onClick={()=>setLocale('en')}>EN</button></div>}
