import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {ApiClient,CapabilityNotice,DashboardShell,Field,JsonDisclosure,KeyValue,LocaleProvider,PageHeader,Panel,RemoteState,SelectField,StatusChip,SubmitButton,TextAreaField,formatServerDate,loadRuntimeConfig,useHashRoute,useMutation,useRemote} from '@kombe/dashboard-core';
import {OperationsApi} from './api';
const messages={app:{fr:'Opérations & Support',en:'Operations & Support'}} as const;
const NAV=[{path:'/',label:'Vue d’ensemble',icon:'◫'},{path:'/jit',label:'Accès JIT',icon:'🔐'},{path:'/actions',label:'Actions support',icon:'⌘'},{path:'/security',label:'Sécurité',icon:'🛡'},{path:'/privacy',label:'Données personnelles',icon:'◉'},{path:'/incidents',label:'Incidents & runbooks',icon:'!'},{path:'/audit',label:'Audit support',icon:'⌁'}] as const;
function Overview({api}:{api:OperationsApi}){const q=useRemote(s=>api.health(s),[api]);return <><PageHeader title="Opérations KÓMBE" description="Connectivité réelle et capacités C17. Aucun voyant n’est mis au vert sans réponse d’une source réelle."/><div className="k-grid"><div className="k-span-6"><Panel title="Santé API"><RemoteState state={q.state} onRetry={q.reload}>{d=><JsonDisclosure value={d}/>}</RemoteState></Panel></div><div className="k-span-6"><Panel title="Garde-fous"><KeyValue label="Accès sensible" value="JIT + double approbation"/><KeyValue label="Pouvoir financier" value={<StatusChip status="Interdit" tone="danger"/>}/><KeyValue label="MFA" value="Exigé par C17"/></Panel></div></div></>}
function CreateJit({api}:{api:OperationsApi}){const[rid,setRid]=useState('');const[gid,setGid]=useState('');const[motif,setMotif]=useState('');const[ttl,setTtl]=useState('900');const[permission,setPermission]=useState('view_trace');const m=useMutation(()=>api.createAccess({requestId:rid.trim(),targetGroupId:gid.trim(),motif:motif.trim(),permissions:[permission],ttlSeconds:Number(ttl)}));return <Panel title="Nouvelle demande JIT"><form onSubmit={e=>{e.preventDefault();m.run(undefined)}}><Field label="Request ID" inputProps={{value:rid,onChange:e=>setRid(e.target.value),required:true,maxLength:120}}/><Field label="Groupe cible" inputProps={{value:gid,onChange:e=>setGid(e.target.value),required:true,maxLength:120}}/><TextAreaField label="Motif" textareaProps={{value:motif,onChange:e=>setMotif(e.target.value),required:true,maxLength:500}}/><SelectField label="Permission" selectProps={{value:permission,onChange:e=>setPermission(e.target.value)}}><option value="view_trace">Voir la trace</option><option value="restore_access">Restaurer l’accès</option><option value="explain_journal">Expliquer le journal</option></SelectField><Field label="TTL (secondes)" inputProps={{type:'number',min:60,max:86400,value:ttl,onChange:e=>setTtl(e.target.value),required:true}}/><SubmitButton busy={m.state.kind==='submitting'}>Créer la demande</SubmitButton></form>{m.state.kind==='success'&&<JsonDisclosure value={m.state.data}/>}</Panel>}
function Lookup({api}:{api:OperationsApi}){const[gid,setGid]=useState('');const[rid,setRid]=useState('');const[key,setKey]=useState<{g:string;r:string}|null>(null);const q=useRemote(s=>api.getAccess(key!.g,key!.r,s),[api,key],{enabled:!!key});return <Panel title="Consulter une demande"><form onSubmit={e=>{e.preventDefault();setKey({g:gid.trim(),r:rid.trim()})}}><Field label="Groupe" inputProps={{value:gid,onChange:e=>setGid(e.target.value),required:true}}/><Field label="Request ID" inputProps={{value:rid,onChange:e=>setRid(e.target.value),required:true}}/><button className="k-button k-button-secondary">Consulter</button></form><RemoteState state={q.state} onRetry={q.reload}>{d=><><KeyValue label="État" value={<StatusChip status={d.status} tone={d.status==='granted'?'ok':d.status==='revoked'?'danger':'warn'}/>}/><KeyValue label="Approbations" value={`${d.approverCount}/${d.requiredApprovals}`}/><KeyValue label="Demandé" value={formatServerDate(d.requestedAt*1000)}/><KeyValue label="Expiration" value={d.expiresAt?formatServerDate(d.expiresAt*1000):'—'}/><JsonDisclosure value={d}/></>}</RemoteState></Panel>}
function Jit({api}:{api:OperationsApi}){return <><PageHeader title="Accès support JIT" description="Accès temporaire borné, double approbation et expiration serveur."/><div className="k-grid"><div className="k-span-6"><CreateJit api={api}/></div><div className="k-span-6"><Lookup api={api}/></div></div></>}
function Actions({api}:{api:OperationsApi}){const[rid,setRid]=useState('');const[version,setVersion]=useState('1');const[action,setAction]=useState('view_trace');const m=useMutation(()=>api.perform(rid.trim(),action,Number(version)));return <><PageHeader title="Actions support" description="Le domaine refuse toute action financière, indépendamment de l’interface."/><Panel><form onSubmit={e=>{e.preventDefault();m.run(undefined)}}><Field label="Request ID" inputProps={{value:rid,onChange:e=>setRid(e.target.value),required:true}}/><SelectField label="Action" selectProps={{value:action,onChange:e=>setAction(e.target.value)}}><option value="view_trace">Voir trace</option><option value="restore_access">Restaurer accès</option><option value="explain_journal">Expliquer journal</option></SelectField><Field label="Version attendue" inputProps={{type:'number',min:1,value:version,onChange:e=>setVersion(e.target.value),required:true}}/><SubmitButton busy={m.state.kind==='submitting'}>Exécuter via le serveur</SubmitButton></form>{m.state.kind==='success'&&<JsonDisclosure value={m.state.data}/>}</Panel></>}
function Security(){return <><PageHeader title="Sécurité opérationnelle" description="Les preuves runtime doivent venir d’une source de sécurité réelle."/><div className="k-grid"><div className="k-span-6"><CapabilityNotice title="Journal sécurité non exposé" contract="GET /support/security-events">C17 possède le journal côté domaine/DB, mais l’OpenAPI ne publie pas encore sa lecture.</CapabilityNotice></div><div className="k-span-6"><CapabilityNotice title="Posture CSP/HSTS/MFA non simulée">Aucun badge de conformité n’est calculé localement sans source runtime.</CapabilityNotice></div></div></>}
function Privacy(){return <><PageHeader title="Données personnelles" description="Les droits C16 existent, mais la file opérateur globale n’est pas publiée."/><CapabilityNotice title="Pas de file globale inventée" contract="GET /v1/privacy/rights-requests?scope=support">Le dashboard attend le contrat serveur de lecture globale.</CapabilityNotice></>}
function Incidents(){return <><PageHeader title="Incidents & runbooks" description="S1 fuite, S2 indisponibilité, S3 canal."/><CapabilityNotice title="Aucune simulation d’incident">Cette page s’activera sur une source d’incidents réelle. Aucun incident de démonstration n’est injecté.</CapabilityNotice></>}
function Audit(){return <><PageHeader title="Audit support" description="Traçabilité des accès JIT et actions support."/><CapabilityNotice title="Recherche transverse non exposée" contract="GET /support/audit">Le journal existe côté serveur ; sa consultation globale reste à contractualiser.</CapabilityNotice></>}
function Dashboard({api,environment}:{api:OperationsApi;environment?:string}){const{path,navigate}=useHashRoute();let page:ReactNode;switch(path){case'/jit':page=<Jit api={api}/>;break;case'/actions':page=<Actions api={api}/>;break;case'/security':page=<Security/>;break;case'/privacy':page=<Privacy/>;break;case'/incidents':page=<Incidents/>;break;case'/audit':page=<Audit/>;break;default:page=<Overview api={api}/>;}return <DashboardShell product="Opérations & Support" nav={NAV} activePath={path} onNavigate={navigate} {...(environment!==undefined?{environment}:{})}>{page}</DashboardShell>}
export function App(){const[ready,setReady]=useState<{api:OperationsApi;environment?:string}|null>(null);const[error,setError]=useState<unknown>(null);useEffect(()=>{loadRuntimeConfig().then(c=>setReady({api:new OperationsApi(new ApiClient({baseUrl:c.apiBaseUrl})),...(c.environment!==undefined?{environment:c.environment}:{})})).catch(setError)},[]);if(error)return <main><CapabilityNotice title="Configuration API absente">{error instanceof Error?error.message:String(error)}</CapabilityNotice></main>;if(!ready)return <main><div className="k-skeleton-stack"><span className="k-skeleton"/></div></main>;return <LocaleProvider messages={messages}><Dashboard {...ready}/></LocaleProvider>}
